name: Weekly Update Index

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - master
jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the update-index.py script
      - name: Run update-index.py
        env:
          GH_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
        run: |
          python update-index.py

      # Commit and push the changes to the repository
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
