name: Weekly Update Index

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - master
jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Run the update-index.py script
    - name: Run update-index.py
      run: |
        python update-index.py
      env:
        X_GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}

    # Commit and push the changes to the repository
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add .
        git commit -m "Update indexes"
        git push
